### ISSUE TITLE
OriginalSource location

### ISSUE THREAD

**Issue by tauren** [Karify/external-svg-sprite-loader#1]
It appears that webpack changed since you published.

```
Error: Cannot find module 'webpack/lib/OriginalSource'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/tauren/repos/exp/node_modules/external-svg-sprite-loader/lib/SvgStorePlugin.js:4:24)
```

I believe you need to import `webpack-sources/lib/OriginalSource` in SvgStorePlugin.js.

However, after change this, I'm getting another error:

```
/Users/tauren/repos/exp/node_modules/external-svg-sprite-loader/lib/SvgStorePlugin.js:40
    constructor({
               ^

TypeError: Cannot match against 'undefined' or 'null'.
    at new SvgStorePlugin (/Users/tauren/repos/exp/node_modules/external-svg-sprite-loader/lib/SvgStorePlugin.js:40:16)
    at module.exports (/Users/tauren/repos/exp/internals/webpack/webpack.base.babel.js:87:5)
```

This is resolved by explicitly passing `true` in the webpack plugins config:

```
 new SvgStorePlugin(true)
```

**Comment by bensampaio** [comment]
Hi @tauren, can you please tell me the version of NodeJS, npm, and webpack you are using? Thank you!

**Comment by tauren** [comment]
@bensampaio I'm using a fresh install of react-boilerplate@3.2.1 which includes webpack@2.1.0-beta.22. I'm running on node@6.9.1 with npm@4.0.0. I added external-svg-sprite-loader@1.0.0 to the project.

Also, your readme shows how to configure webpack, but it doesn't show any usage. Could you provide some hints or docs on how to utilize the SVG sprites? Especially in an ES6 react project?

Thanks!

**Comment by bensampaio** [comment]
@tauren we are only focusing on supporting stable releases of webpack. Webpack 2 is still in beta, so we won't support it for now.

I fixed the problem with the plugin constructor on version 1.0.1. You can now initialise it without any params.

I will improve the README with some example on how to use this loader both in JS and CSS. Thanks!

**Comment by satazor** [comment]
@bensampaio now that webpack 2 is released, are there any plans to make it work?

**Comment by bensampaio** [comment]
Yes, I have to look into this. I'll try to make it work on the coming days.
