### ISSUE TITLE
Hot module reload

### ISSUE THREAD

**Issue by satazor** [karify/external-svg-sprite-loader#14]
I've setup hot module reload on a project and it's working nicely, except when adding/removing/editing svgs that go through this loader.

Maybe that's something that we could improve? See style-loader for an example: https://github.com/webpack-contrib/style-loader/blob/master/index.js#L21

**Comment by bensampaio** [comment]
@satazor, I don't think I'll be able to work on this any time soon. But feel free submit a PR. I will be happy to review it :)
