### ISSUE TITLE
Usage in HTML / Pug files?

### ISSUE THREAD

**Issue by michaelpumo** [karify/external-svg-sprite-loader#16]
This loader looks great and I can get it to build the SVG files just fine.

However, I'm unsure how to use this within my HTML / Pug files? I can't see an example showing this at all.

Because the ID's are generated from their original file names and then made unique, I'm unable to reference them. e.g. If I have an SVG like 'mark.svg', I'm unable to do:

```
<svg class="c-splash__mark">
<use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="svg/sprite.svg#mark"></use>
</svg>
```

...because the resulting ID is something like '-mark-97878'. 

I can see how to use this in JS, but would be great to see an example with just straight HTML. I'm actually using Pug templates though.

Or, is there an option to keep the ID's the same as the original filenames? That way I already know how to link to it.

Apologies if this is not an 'issue' per se, but thought it might help give some more thought to the documentation in the process?

Thank you!

**Comment by bensampaio** [comment]
@michaelpumo this loader was built with JS in mind, so I never thought about this use case. I could provide an option to change the icons names, that would actually make sense. But if you don't use an hash then you need to make sure your SVG files have unique names. What do you think of that?

In any case, I think you could use the [html-loader](https://github.com/webpack-contrib/html-loader) and / or the [pug-loader](https://github.com/pugjs/pug-loader) to achieve what you are trying to do. I haven't tested it so maybe I am wrong.

**Comment by michaelpumo** [comment]
I think this would be a great addition!

Simply to have an option that only takes the filenames as the ID's I think would be fine because the filenames themselves have to be unique when in the same folder anyway. 

This is what I currently do using a Gulp task and never have issues here. 

Not looked into using those loaders as I'm still finding my way with webpack. Thanks for the heads up. 

Is this a realistically feesible feature? It would make building static HTML sites so much easier. 

Thanks

**Comment by bensampaio** [comment]
I agree with the option and I created the PR https://github.com/karify/external-svg-sprite-loader/pull/17 for it just now. However, I think you should be using some additional loader (as I mentioned above) because what you are trying to do isn't really the webpack way :p

**Comment by bensampaio** [comment]
Just released version 2.2.0. You now have the `iconName` option. For your case you can change it to `icon-[name]` and icon names will no longer be hashed. Hope it works!

**Comment by michaelpumo** [comment]
Thank you very much for this. I haven't tried it yet, but I appreciate your hard work and will let you know if there's any problems! 🙏🏼

**Comment by michaelpumo** [comment]
@bensampaio When I run `yarn` on my `package.json` that specifies version `2.2.0` - what I actually seem to get is version `2.1.2`.

I'm not sure if this is a separate issue. The code for your loader in my node_modules does not reflect the code you have on your GitHub repository. In the `package.json`, it tells me version `2.1.2`.

Because of this, the suggested solution / fix you did does not work, because I don't have these new updates. Not sure what's happening here?

Funny enough, even trying to pull from the repo on GitHub directly does not seem to get this latest version you have:

`"external-svg-sprite-loader": "https://github.com/karify/external-svg-sprite-loader.git"`

Perhaps I am missing something very obvious here?

Thanks!

**Comment by bensampaio** [comment]
@michaelpumo yarn saves the last installed version on the lock file and will always install that one everytime you run `yarn`. To install the most recent version you need to run `yarn upgrade external-svg-sprite-loader`. Or to update all your dependencies just run `yarn upgrade`. This is one of the reasons why `yarn` was invented :)
