### ISSUE TITLE
Outputting stringified object

### ISSUE THREAD

**Issue by timkelty** [karify/external-svg-sprite-loader#18]
```
.foo {
  background: url("data:image/svg+xml,module.exports = %7B symbol: './sprite.260eb415c771c8a967d00f1e5992e300.bundle.svg%23icon-logo-c2a81', view: './sprite.260eb415c771c8a967d00f1e5992e300.bundle.svg%23view-icon-logo-c2a81', viewBox: '0 0 111.9 57.29', toString: function () %7B return this.view; %7D %7D;");
}
```

My svg sprite is getting generated, but when I require svgs (in both css and js), I get back a string (see above). Any idea why?

**Comment by timkelty** [comment]
Figured this out - I had `url-loader` before `external-svg-sprite-loader` in my `svg` rule.
I'll leave this open if you think there is a fix that would have it work in both cases.

**Comment by bensampaio** [comment]
I don't think the `url-loader` can be combined with this loader. They have totally different goals. The `url-loader` converts files to a string or returns the file itself, while the `external-svg-sprite-loader` merges all the files into a sprite and replaces the file with a JS object. They are not meant to be used together. If you need both on your project then you need a more specific `test` regex for each one in your webpack config. For example: maybe you want all SVGs in the `icons` folder to be parsed by `external-svg-sprite-loader` and all SVGs in the `images` folder to be parsed by `url-loader`.

**Comment by timkelty** [comment]
Makes sense. Thanks for the reply.
I only ran into it because I was using URL loader in my SVG rule and added this to it, rather than replacing it.
