### ISSUE TITLE
Module build failed: TypeError: Cannot match against 'undefined' or 'null'.

### ISSUE THREAD

**Issue by bullwinkle** [karify/external-svg-sprite-loader#19]
![image](https://cloud.githubusercontent.com/assets/3613558/24896803/39e7e764-1e9f-11e7-88c3-2efa07bbc082.png)

The .svg file is exists, fine and works with other loaders (for example https://www.npmjs.com/package/svg-sprite-loader).

`ERROR in ./src/assets/svg/anchor.svg
Module build failed: TypeError: Cannot match against 'undefined' or 'null'.
    at Object.loader (/Users/macbookpro/Projects/ulmart-mobile.mobile/node_modules/external-svg-sprite-loader/index.js:37:39)
 @ ./src/app/app.module.js 13:10-45
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://0.0.0.0:9008 main.js
`

In `external-svg-sprite-loader/index.js` on line 37 you've got this:
`const { addDependency, cacheable, resourcePath, options: { output: { publicPath } } } = this;`,
but there is no `options` in webpack object, there is `_compilation.outputOptions.publicPush`, so you need to replace this line with this one
`const { addDependency, cacheable, resourcePath, _compilation.outputOptions: { outputOptions: { publicPath } } } = this;` and everything will work.

Please, tell me if i`am not right.

**Comment by bensampaio** [comment]
@bullwinkle which version of webpack are you using? I don't have this problem, but apparently both `options` and `_compilation` were deprecated so your solution would also not be future proof. I will look into this.

**Comment by bensampaio** [comment]
I opened a question on StackOverflow: http://stackoverflow.com/questions/43373376/how-to-access-the-webpack-config-with-the-new-loader-api.

**Comment by bullwinkle** [comment]
First of all i want to say that this is a helpful tool and thank you for your work.
webpack "version": "2.3.3"
Yes, i understand, that `_compilation` is deprecated and my solution is not solution in common, just the way to show that it can works. In my case i`ve fall into debug and saw that webpack object have ho field `options` at all. So may be some fixes needed.

**Comment by bullwinkle** [comment]
I can`t find info about deprecating `_compilation`. Seems it is a usable solution.
https://webpack.js.org/api/loaders/#this-_compilation

**Comment by bensampaio** [comment]
If you go a bit up in that page you will see the following header: `Deprecated context properties`

**Comment by bullwinkle** [comment]
ah, yes, you are right :)) so, we need an alternative solution... maybe ask Sokra ?

**Comment by bensampaio** [comment]
I would say an alternative solution would be to pass the `publicPath` as an option to this loader. But maybe there is another way to do this now and that's why those properties are being deprecated. How do you propose I contact Sokra? Questions don't seem to be allowed on the webpack repo and Sokra has no contact information. Maybe you can upvote my question on StackOverflow so it gets more visibility? :)

**Comment by bullwinkle** [comment]
@sokra

**Comment by mattybow** [comment]
posted a possible solution here http://stackoverflow.com/questions/43373376/how-to-access-the-webpack-config-with-the-new-loader-api/43532591#43532591

**Comment by bensampaio** [comment]
This should be fixed on v2.2.1. Let me know if that's not the case :)

**Comment by bullwinkle** [comment]
Will be great
