### ISSUE TITLE
Styles are not interpreted in `<use>` Tag

### ISSUE THREAD

**Issue by chmanie** [karify/external-svg-sprite-loader#21]
The colors of my icons are missing as the styles not seem to be interpreted for the icons with classNames.

`<symbol>` definition in the sprite:

```xml
<symbol xmlns="http://www.w3.org/2000/svg" id="icon-logo-d32ed" viewBox="0 0 957.31 481.44">
  <defs>
    <style>.cls-1{fill:#7cd6df}</style>
  </defs>
  <path class="cls-1" d="OMITTED"/>
  <!-- More paths -->
</symbol>
```
`<view>` definition in the sprite:

```xml
<view xmlns="http://www.w3.org/2000/svg" id="view-icon-logo-d32ed" viewBox="0 0 99.48 50"/>
```

`<use>` definition in the sprite:

```xml
<use xmlns="http://www.w3.org/2000/svg" id="icon-logo-d32ed" xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#icon-logo-d32ed" width="99.48" height="50" x="0" y="0"/>
```

`<svg>` in the page:

```xml
<svg><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="/static/img/sprite.svg#icon-logo-d32ed"></use></svg>
```

Is there a way to not lose the styles in the page?

**Comment by bensampaio** [comment]
@chmanie have you passed custom svgo options? I think the option `convertStyleToAttrs` is mandatory for the sprite to work as expected. Your `<symbol>` should look like:
```xml
<symbol xmlns="http://www.w3.org/2000/svg" id="icon-logo-d32ed" viewBox="0 0 957.31 481.44">
  <path fill="#7cd6df" d="OMITTED"/>
  <!-- More paths -->
</symbol>
```

**Comment by chmanie** [comment]
@bensampaio thank you very much for your answer! I think that won't work in my case as it just transforms `style=` tags. But this here probably will:

https://github.com/svg/svgo/pull/592

Closing this as it is not in the responsibiliy of this lib to do that :)
