### ISSUE TITLE
If `ExtractedModule` is null the code fails to compile

### ISSUE THREAD

**Issue by leidegre** [karify/external-svg-sprite-loader#33]
See https://github.com/karify/external-svg-sprite-loader/blob/90e052a7463a934927dc12f0d156d5ff67fd4a50/lib/SvgStorePlugin.js#L118

I get the following error:

~~~
TypeError: Right-hand side of 'instanceof' is not an object
    at chunk.modules.forEach (node_modules\external-svg-sprite-loader\lib\SvgStorePlugin.js:118)
~~~

I the `extract-text-webpack-plugin` must have change because it does not appear to export `ExtractedModule` any longer.

Adding an additional statement like this, at the top of the file, would solve this issue.

~~~
if (!ExtractedModule) {
  try {
    ExtractedModule = require('extract-text-webpack-plugin/dist/lib/ExtractedModule').default;
  }
  catch (e) {
    ExtractedModule = null;
  }
}
~~~

**Comment by bensampaio** [comment]
@leidegre which version of `extract-text-webpack-plugin` are you using?

**Comment by leidegre** [comment]
`extract-text-webpack-plugin@3.0.0`

I had to move on so I work around it as best I could.

**Comment by bensampaio** [comment]
The file `extract-text-webpack-plugin/dist/lib/ExtractedModule` exists on version 3. It is generated during install of the package. Which version of `npm` or `yarn` are you using? Maybe that's the issue.

**Comment by leidegre** [comment]
`yarn@0.24.4`

**Comment by bensampaio** [comment]
This problem will be fixed in version 4.
