### ISSUE TITLE
[hash] is not stable

### ISSUE THREAD

**Issue by leidegre** [karify/external-svg-sprite-loader#35]
I've run into an issue with the usage of `[hash]`. It's not stable, i.e. it does not produce consistent results. Multiple builds -> different hashes. This breaks long term caching.

I'm also running into a problem where client and server compilation passes are running in different processes and produce different hashes for the exact same code.

The results in the SSR pass emitting incorrect asset paths that then break client hydration (React).

I'm going to suggest a fix for this.

**Comment by leidegre** [comment]
A very simple way to fix this is just to make sure that the files are fed into the processing in a stable sort order. Like this:

`[SvgSprite.js:91]`
~~~
        const iconsSorted = Object.keys(icons)
        iconsSorted.sort()
        for (let i = 0; i < iconsSorted.length; i++) {
            let iconPath = iconsSorted[i]
            ...
~~~

**Comment by bensampaio** [comment]
@leidegre good find! I was having the same problem but didn't know what could be causing it. I will create an MR for this.

**Comment by bensampaio** [comment]
@leidegre can you let me know if #35 fix the issue for you?

**Comment by leidegre** [comment]
@bensampaio as soon as I have a moment to test this, I will. But it should work.
