### ISSUE TITLE
x='NaN'

### ISSUE THREAD

**Issue by gmdvdv** [karify/external-svg-sprite-loader#40]
<use id="strelka" xlink:href="#strelka" width="78.75" height="50" **x="NaN"** y="0"></use>
  <use id="test_stand" xlink:href="#test_stand" width="33.25" height="50" **x="NaN"** y="0"></use>
  <use id="tractor" xlink:href="#tractor" width="33.25" height="50" **x="NaN"** y="0"></use>
  <use id="tractor_car" xlink:href="#tractor_car" width="33.25" height="50" **x="NaN"** y="0"></use>
  <use id="train" xlink:href="#train" width="33.25" height="50" **x="NaN"** y="0"></use>

**"external-svg-sprite-loader": "^3.3.0"**

**Comment by bensampaio** [comment]
@gmdvdv sorry for the delay, I was on holidays when you reported this and I ended up forgetting about it. Are you still experiencing this problem? Could you give an example of svgs you are using? Thank you!

**Comment by usebaz** [comment]
@bensampaio in my case it reproduces when `external-svg-sprite-loader` try add to build svg font, and function:
https://github.com/karify/external-svg-sprite-loader/blob/8c57bd4cba28261fcfb7b299363b1aac462e5e13/lib/SvgSprite.js#L117

return `width: NaN`

maybe need add warning or error for easy debug it's case?

**Comment by usebaz** [comment]
not, not have. But I think loader must throw error or ignore this file and show warning

**Comment by bensampaio** [comment]
@usebaz can you check if version 4.0.0-beta.6 fixes your problem? :)
