### ISSUE TITLE
Access all the sprites in the SvgStore plugin

### ISSUE THREAD

**Issue by satazor** [karify/external-svg-sprite-loader#41]
I have a use-case where I need to get access to produced sprites after a webpack build, that is, every sprite metadata.

At the moment, there's `getSpritesWithInterpolateName` that accomplishes what I want except that it returns `[]` in DEV because I'm not using `[hash]` in development.

I will make a PR that adds this new method.

**Comment by bensampaio** [comment]
Could you describe your use case so that I know why this change is necessary?

**Comment by satazor** [comment]
Because the strategy that this plugin uses does not allow the sprite file to be served via cross-domain request, see https://github.com/karify/external-svg-sprite-loader/issues/37.

In our projects, we produce a `manifest.json` that contains all the asset URLs and use them to load JS and CSS files as well as prefetching/preloading assets. But since we are changing the publicPath of the `external-svg-sprite-loader` to be a non-CDN url, we must ensure that the SVG sprites present in the `manifest.json` are correct. More specifically, the URLs of the sprite must not use the webpack publicPath config but instead the URL that pass to `external-svg-sprite-loader` (non-CDN url).

**Comment by satazor** [comment]
I've edited my comment to be more complete.

**Comment by bensampaio** [comment]
Hmm I understand the problem. Are you also using `webpack-manifest-plugin`? Maybe there is a way of communicating a different publicPath to other plugins? Maybe we can set some webpack property in order to change the path for a specific chunk. Have you looked into that? Maybe we can even find other plugins with a similar problem? Would be interesting to know if that's actually possible. The solution you proposed on the PR might work but feels a bit like a workaround to something that might have a better solution.

**Comment by satazor** [comment]
We are not using `webpack-manifest-plugin` but we are doing something similar. Some plugins, such as this one, support overriding the publicPath. Though, this publicPath override is not available in the [compilation](https://github.com/danethurber/webpack-manifest-plugin/blob/409b0fb64234ed9fa9adeeba31850a4d4feeca7c/lib/plugin.js#L46) nor the stats, which are used by tools like `webpack-manifest-plugin`.

Because of this reason, `webpack-manifest-plugin` offers `options.map` and `options.generate` to allow consumers to change the public path from the outside. Though, we need to know which assets were produced by the `external-svg-sprite-loader`. One could obviously search for assets by a prefix, e.g.: `svg-sprite-*` but it would be a poor solution.

**Comment by satazor** [comment]
Bump.
