### ISSUE TITLE
Bad behavior when using multiple instances of the plugin

### ISSUE THREAD

**Issue by satazor** [karify/external-svg-sprite-loader#53]
When using multiple plugin instances when compiling, e.g.: doing a client & server build, there's some unexpected behavior. The reason is that my last PR added state to the SvgSprite class which is shared among the different plugin instances. This causes the `updated` flag to be out-of-sync, which in turn causes the replacements to be skipped.

To solve this issue, we need to move all this "stateful" flags to the SvgStorePlugin instead. I will be making a PR soon.

**Comment by bensampaio** [comment]
Fixed in https://github.com/karify/external-svg-sprite-loader/pull/54

**Comment by satazor** [comment]
Awesome!
