### ISSUE TITLE
Using `webpack-chain` breaks default options

### ISSUE THREAD

**Issue by ashleahhill** [karify/external-svg-sprite-loader#63]
Hello,

I am setting up a Vue.js project using Vue CLI 3.8.4. Therefore I have to use `webpack-chain` to configure this plugin. Because `oneOf` in `webpack-chain` sets an `options` prop on the rule, (as `undefined`) `SvgStorePlugin#injectSpriteIntoRule` errors:

```
ypeError: Cannot read property 'name' of undefined
    at SvgStorePlugin.injectSpriteIntoRule (/node_modules/external-svg-sprite-loader/lib/SvgStorePlugin.js:151:43)

```

Basically this check:

```
if (!('options' in rule)) {
  rule.options = {};
}
```

Isn't enough.

I'm able to work around it by setting my own name in my config like this:

```
webpackChainConfig.module
      .rule('svg')
        .uses.clear()
        .end()
...
        .oneOf('sprite')
          .test(/sprite/)
            .use('external-svg-sprite-loader')
              .loader(SvgStorePlugin.loader)
              .options({
                name: 'img/sprite.svg',
              })
            .end()
```

**Comment by bensampaio** [comment]
This should be fixed on v5.0.1
