### ISSUE TITLE
deprecation warning for chunk.files in webpack 5

### ISSUE THREAD

**Issue by thasmo** [karify/external-svg-sprite-loader#70]
[This line](https://github.com/karify/external-svg-sprite-loader/blob/c2fd5f7897f76a2c11b9667391fce8fdefa20c99/lib/SvgStorePlugin.js#L247) triggers a deprecation warning in webpack 5:
```
[DEP_WEBPACK_DEPRECATION_ARRAY_TO_SET_PUSH] DeprecationWarning: chunk.files was changed from Array to Set (using Array method 'push' is deprecated)
```

**Comment by bensampaio** [comment]
@thasmo thank you for reporting this issue. I created a PR that should fix this: https://github.com/karify/external-svg-sprite-loader/pull/71. Could you check if you still get this warning when using my changes?
