### ISSUE TITLE
Breaks with mini-css-extract-plugin@1.3.0

### ISSUE THREAD

**Issue by mihkeleidast** [karify/external-svg-sprite-loader#88]
Webpack build fails when using both mini-css-extract-plugin@1.3.0 and external-svg-sprite-loader.

I created a repo with repro: https://github.com/mihkeleidast/webpack-css-svg-issue

I originally reported this to mini-css-extract-plugin but I was told this should be fixed here: https://github.com/webpack-contrib/mini-css-extract-plugin/issues/653

**Comment by bensampaio** [comment]
Hmm this is an issue 😬 Thanks for reporting, though! I don't have an immediate solution for this issue so I recommend sticking to 1.2.0 if that is working for you.

**Comment by bensampaio** [comment]
@mihkeleidast could you let me know if this issue is fixed when using external-svg-sprite-loader@7.1.0-beta.0?

**Comment by mihkeleidast** [comment]
Yes, with the beta the build succeeds.
